=== atelper1005/AntonioTellez.UD4.LMSGI/Actividad6.Modulos/Modulos.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
version="0.1" xml:lang="es">
	<xs:element name="Modulo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Nombre" type="xs:string" />
				<xs:element name="Contenidos" type="tipoContenidos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="tipoContenidos">
		<xs:sequence>
			<xs:element name="Bloque" type="tipoBloque" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="tipoBloque">
		<xs:sequence>
			<xs:element name="Titulo" type="xs:string" />
			<xs:element name="Descripcion" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== atelper1005/AntonioTellez.UD4.LMSGI/Actividad6.Modulos/Modulos.xml
<?xml version="1.0" encoding="UTF-8"?>
 <Modulo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Modulos.xsd">
       <Nombre>Programacion</Nombre>
       <Contenidos>
             <Bloque>
                   <Titulo>Introducción a Java</Titulo>
                   <Descripcion>Unidades más básicas para construcción de código Java</Descripcion>
             </Bloque>
             <Bloque>
                   <Titulo>Método Main</Titulo>
                   <Descripcion>Punto en el que comienza la ejecución de una aplicación Java</Descripcion>
             </Bloque>
             <Bloque>
                   <Titulo>Clases y sus atributos</Titulo>
                   <Descripcion>Herencia y polimorfismo</Descripcion>
             </Bloque>
             <Bloque>
                   <Titulo>Arrays</Titulo>
                   <Descripcion>Comparar, eliminar, crear y recorrer</Descripcion>
             </Bloque>
       </Contenidos>
 </Modulo>
